// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bls.proto

/*
Package bls is a generated protocol buffer package.

It is generated from these files:
	bls.proto

It has these top-level messages:
	SignRequest
	SignReply
	SendSignature
*/
package bls

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignRequest struct {
	// string data = 1;
	SharedParams string `protobuf:"bytes,1,opt,name=sharedParams" json:"sharedParams,omitempty"`
	SharedG      []byte `protobuf:"bytes,2,opt,name=sharedG,proto3" json:"sharedG,omitempty"`
}

func (m *SignRequest) Reset()                    { *m = SignRequest{} }
func (m *SignRequest) String() string            { return proto.CompactTextString(m) }
func (*SignRequest) ProtoMessage()               {}
func (*SignRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SignRequest) GetSharedParams() string {
	if m != nil {
		return m.SharedParams
	}
	return ""
}

func (m *SignRequest) GetSharedG() []byte {
	if m != nil {
		return m.SharedG
	}
	return nil
}

type SignReply struct {
	Data      string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Publickey []byte `protobuf:"bytes,3,opt,name=publickey,proto3" json:"publickey,omitempty"`
}

func (m *SignReply) Reset()                    { *m = SignReply{} }
func (m *SignReply) String() string            { return proto.CompactTextString(m) }
func (*SignReply) ProtoMessage()               {}
func (*SignReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SignReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *SignReply) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignReply) GetPublickey() []byte {
	if m != nil {
		return m.Publickey
	}
	return nil
}

type SendSignature struct {
	Data         string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Signature    []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SharedParams string `protobuf:"bytes,3,opt,name=SharedParams" json:"SharedParams,omitempty"`
	SharedG      []byte `protobuf:"bytes,4,opt,name=SharedG,proto3" json:"SharedG,omitempty"`
}

func (m *SendSignature) Reset()                    { *m = SendSignature{} }
func (m *SendSignature) String() string            { return proto.CompactTextString(m) }
func (*SendSignature) ProtoMessage()               {}
func (*SendSignature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SendSignature) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *SendSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SendSignature) GetSharedParams() string {
	if m != nil {
		return m.SharedParams
	}
	return ""
}

func (m *SendSignature) GetSharedG() []byte {
	if m != nil {
		return m.SharedG
	}
	return nil
}

func init() {
	proto.RegisterType((*SignRequest)(nil), "bls.SignRequest")
	proto.RegisterType((*SignReply)(nil), "bls.SignReply")
	proto.RegisterType((*SendSignature)(nil), "bls.SendSignature")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SignService service

type SignServiceClient interface {
	SignString(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignReply, error)
	SendSign(ctx context.Context, in *SendSignature, opts ...grpc.CallOption) (*SignReply, error)
}

type signServiceClient struct {
	cc *grpc.ClientConn
}

func NewSignServiceClient(cc *grpc.ClientConn) SignServiceClient {
	return &signServiceClient{cc}
}

func (c *signServiceClient) SignString(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignReply, error) {
	out := new(SignReply)
	err := grpc.Invoke(ctx, "/bls.SignService/SignString", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signServiceClient) SendSign(ctx context.Context, in *SendSignature, opts ...grpc.CallOption) (*SignReply, error) {
	out := new(SignReply)
	err := grpc.Invoke(ctx, "/bls.SignService/SendSign", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SignService service

type SignServiceServer interface {
	SignString(context.Context, *SignRequest) (*SignReply, error)
	SendSign(context.Context, *SendSignature) (*SignReply, error)
}

func RegisterSignServiceServer(s *grpc.Server, srv SignServiceServer) {
	s.RegisterService(&_SignService_serviceDesc, srv)
}

func _SignService_SignString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignServiceServer).SignString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bls.SignService/SignString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignServiceServer).SignString(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignService_SendSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSignature)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignServiceServer).SendSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bls.SignService/SendSign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignServiceServer).SendSign(ctx, req.(*SendSignature))
	}
	return interceptor(ctx, in, info, handler)
}

var _SignService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bls.SignService",
	HandlerType: (*SignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignString",
			Handler:    _SignService_SignString_Handler,
		},
		{
			MethodName: "SendSign",
			Handler:    _SignService_SendSign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bls.proto",
}

func init() { proto.RegisterFile("bls.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x09, 0xa9, 0x80, 0x1c, 0x01, 0xa1, 0x9b, 0x22, 0xc4, 0x50, 0x79, 0xea, 0x54, 0x55,
	0xf0, 0x23, 0x18, 0x58, 0x50, 0x3c, 0x32, 0xd9, 0xcd, 0x29, 0x58, 0x18, 0xd7, 0xb5, 0x1d, 0xa4,
	0x4c, 0xfc, 0x75, 0xd4, 0xd8, 0x0d, 0x06, 0x26, 0x36, 0xbf, 0xf7, 0x7c, 0x67, 0x7d, 0xcf, 0x50,
	0x49, 0xed, 0xd7, 0xd6, 0xed, 0xc2, 0x0e, 0x4b, 0xa9, 0x3d, 0x7b, 0x82, 0x4b, 0xae, 0x7a, 0xd3,
	0xd2, 0x7e, 0x20, 0x1f, 0x90, 0x41, 0xed, 0x5f, 0x85, 0xa3, 0xee, 0x59, 0x38, 0xf1, 0xee, 0x9b,
	0x62, 0x59, 0xac, 0xaa, 0xf6, 0x87, 0x87, 0x0d, 0x9c, 0x47, 0xfd, 0xd8, 0x9c, 0x2e, 0x8b, 0x55,
	0xdd, 0x1e, 0x25, 0x7b, 0x81, 0x2a, 0x2e, 0xb3, 0x7a, 0x44, 0x84, 0x45, 0x27, 0x82, 0x48, 0x2b,
	0xa6, 0x33, 0xde, 0x41, 0xe5, 0x55, 0x6f, 0x44, 0x18, 0x1c, 0xa5, 0xe1, 0x6f, 0xe3, 0x90, 0xda,
	0x41, 0x6a, 0xb5, 0x7d, 0xa3, 0xb1, 0x29, 0x63, 0x3a, 0x1b, 0xec, 0x13, 0xae, 0x38, 0x99, 0x8e,
	0xcf, 0xd7, 0xff, 0xff, 0x00, 0x83, 0x9a, 0xe7, 0x74, 0x65, 0xa4, 0xe3, 0xbf, 0xe8, 0x78, 0xa2,
	0x5b, 0x44, 0xba, 0x24, 0xef, 0xf7, 0xb1, 0x2a, 0x4e, 0xee, 0x43, 0x6d, 0x09, 0x37, 0x00, 0x93,
	0x0c, 0x4e, 0x99, 0x1e, 0x6f, 0xd6, 0x87, 0x62, 0xb3, 0x2a, 0x6f, 0xaf, 0x33, 0xc7, 0xea, 0x91,
	0x9d, 0xe0, 0x06, 0x2e, 0x8e, 0x04, 0x88, 0x31, 0xcd, 0x81, 0xfe, 0x4e, 0xc8, 0xb3, 0xe9, 0xa7,
	0x1e, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x82, 0xd4, 0x6e, 0xb6, 0x01, 0x00, 0x00,
}
