// Code generated by protoc-gen-go. DO NOT EDIT.
// source: list.proto

/*
Package list is a generated protocol buffer package.

It is generated from these files:
	list.proto

It has these top-level messages:
	InputMsg
	InputResponse
	NodeRequest
	NodeResponse
	Nodes
	LinkRequest
	HelloResponse
*/
package list

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InputMsg struct {
	SharedParams string `protobuf:"bytes,1,opt,name=sharedParams" json:"sharedParams,omitempty"`
	SharedG      []byte `protobuf:"bytes,2,opt,name=sharedG,proto3" json:"sharedG,omitempty"`
}

func (m *InputMsg) Reset()                    { *m = InputMsg{} }
func (m *InputMsg) String() string            { return proto.CompactTextString(m) }
func (*InputMsg) ProtoMessage()               {}
func (*InputMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InputMsg) GetSharedParams() string {
	if m != nil {
		return m.SharedParams
	}
	return ""
}

func (m *InputMsg) GetSharedG() []byte {
	if m != nil {
		return m.SharedG
	}
	return nil
}

type InputResponse struct {
	Resp []byte `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (m *InputResponse) Reset()                    { *m = InputResponse{} }
func (m *InputResponse) String() string            { return proto.CompactTextString(m) }
func (*InputResponse) ProtoMessage()               {}
func (*InputResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InputResponse) GetResp() []byte {
	if m != nil {
		return m.Resp
	}
	return nil
}

// The data that need to be added to the list.
type NodeRequest struct {
	Data int32 `protobuf:"varint,1,opt,name=data" json:"data,omitempty"`
}

func (m *NodeRequest) Reset()                    { *m = NodeRequest{} }
func (m *NodeRequest) String() string            { return proto.CompactTextString(m) }
func (*NodeRequest) ProtoMessage()               {}
func (*NodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NodeRequest) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

// Success or failure message.
type NodeResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *NodeResponse) Reset()                    { *m = NodeResponse{} }
func (m *NodeResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeResponse) ProtoMessage()               {}
func (*NodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Nodes struct {
	Node int32 `protobuf:"varint,1,opt,name=node" json:"node,omitempty"`
}

func (m *Nodes) Reset()                    { *m = Nodes{} }
func (m *Nodes) String() string            { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()               {}
func (*Nodes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Nodes) GetNode() int32 {
	if m != nil {
		return m.Node
	}
	return 0
}

type LinkRequest struct {
}

func (m *LinkRequest) Reset()                    { *m = LinkRequest{} }
func (m *LinkRequest) String() string            { return proto.CompactTextString(m) }
func (*LinkRequest) ProtoMessage()               {}
func (*LinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type HelloResponse struct {
	Reply string `protobuf:"bytes,1,opt,name=reply" json:"reply,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *HelloResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*InputMsg)(nil), "list.InputMsg")
	proto.RegisterType((*InputResponse)(nil), "list.InputResponse")
	proto.RegisterType((*NodeRequest)(nil), "list.NodeRequest")
	proto.RegisterType((*NodeResponse)(nil), "list.NodeResponse")
	proto.RegisterType((*Nodes)(nil), "list.Nodes")
	proto.RegisterType((*LinkRequest)(nil), "list.LinkRequest")
	proto.RegisterType((*HelloResponse)(nil), "list.HelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for List service

type ListClient interface {
	// Adding a new nodes to the linked list
	InsertNode(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	// Printing the Linked List
	Printing(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (List_PrintingClient, error)
	// Trying to get a response
	HelloRelay(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// Sending user input funcationlity
	ProcessInput(ctx context.Context, in *InputMsg, opts ...grpc.CallOption) (*InputResponse, error)
	// Linking to Linked List
	InsertInput(ctx context.Context, in *InputMsg, opts ...grpc.CallOption) (*InputResponse, error)
}

type listClient struct {
	cc *grpc.ClientConn
}

func NewListClient(cc *grpc.ClientConn) ListClient {
	return &listClient{cc}
}

func (c *listClient) InsertNode(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	out := new(NodeResponse)
	err := grpc.Invoke(ctx, "/list.List/InsertNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listClient) Printing(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (List_PrintingClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_List_serviceDesc.Streams[0], c.cc, "/list.List/Printing", opts...)
	if err != nil {
		return nil, err
	}
	x := &listPrintingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type List_PrintingClient interface {
	Recv() (*Nodes, error)
	grpc.ClientStream
}

type listPrintingClient struct {
	grpc.ClientStream
}

func (x *listPrintingClient) Recv() (*Nodes, error) {
	m := new(Nodes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *listClient) HelloRelay(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc.Invoke(ctx, "/list.List/HelloRelay", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listClient) ProcessInput(ctx context.Context, in *InputMsg, opts ...grpc.CallOption) (*InputResponse, error) {
	out := new(InputResponse)
	err := grpc.Invoke(ctx, "/list.List/ProcessInput", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listClient) InsertInput(ctx context.Context, in *InputMsg, opts ...grpc.CallOption) (*InputResponse, error) {
	out := new(InputResponse)
	err := grpc.Invoke(ctx, "/list.List/InsertInput", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for List service

type ListServer interface {
	// Adding a new nodes to the linked list
	InsertNode(context.Context, *NodeRequest) (*NodeResponse, error)
	// Printing the Linked List
	Printing(*LinkRequest, List_PrintingServer) error
	// Trying to get a response
	HelloRelay(context.Context, *NodeRequest) (*HelloResponse, error)
	// Sending user input funcationlity
	ProcessInput(context.Context, *InputMsg) (*InputResponse, error)
	// Linking to Linked List
	InsertInput(context.Context, *InputMsg) (*InputResponse, error)
}

func RegisterListServer(s *grpc.Server, srv ListServer) {
	s.RegisterService(&_List_serviceDesc, srv)
}

func _List_InsertNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).InsertNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.List/InsertNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).InsertNode(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _List_Printing_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LinkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ListServer).Printing(m, &listPrintingServer{stream})
}

type List_PrintingServer interface {
	Send(*Nodes) error
	grpc.ServerStream
}

type listPrintingServer struct {
	grpc.ServerStream
}

func (x *listPrintingServer) Send(m *Nodes) error {
	return x.ServerStream.SendMsg(m)
}

func _List_HelloRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).HelloRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.List/HelloRelay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).HelloRelay(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _List_ProcessInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).ProcessInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.List/ProcessInput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).ProcessInput(ctx, req.(*InputMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _List_InsertInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).InsertInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.List/InsertInput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).InsertInput(ctx, req.(*InputMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _List_serviceDesc = grpc.ServiceDesc{
	ServiceName: "list.List",
	HandlerType: (*ListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertNode",
			Handler:    _List_InsertNode_Handler,
		},
		{
			MethodName: "HelloRelay",
			Handler:    _List_HelloRelay_Handler,
		},
		{
			MethodName: "ProcessInput",
			Handler:    _List_ProcessInput_Handler,
		},
		{
			MethodName: "InsertInput",
			Handler:    _List_InsertInput_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Printing",
			Handler:       _List_Printing_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "list.proto",
}

func init() { proto.RegisterFile("list.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4e, 0x02, 0x31,
	0x10, 0xde, 0x25, 0xa0, 0x38, 0xbb, 0x98, 0x38, 0x7a, 0x20, 0x78, 0xc1, 0x1a, 0x13, 0x4e, 0xc4,
	0xa8, 0xf8, 0x0a, 0x42, 0x82, 0x86, 0xf4, 0x0d, 0x56, 0x76, 0x82, 0x1b, 0xd7, 0x76, 0xed, 0x94,
	0x03, 0xaf, 0xe1, 0x13, 0x9b, 0xb6, 0x5b, 0x85, 0xc4, 0x8b, 0xb7, 0x99, 0xc9, 0xf7, 0xd7, 0x99,
	0x02, 0xd4, 0x15, 0xdb, 0x69, 0x63, 0xb4, 0xd5, 0xd8, 0x75, 0xb5, 0x98, 0x43, 0x7f, 0xa1, 0x9a,
	0xad, 0x7d, 0xe6, 0x0d, 0x0a, 0xc8, 0xf9, 0xad, 0x30, 0x54, 0xae, 0x0a, 0x53, 0x7c, 0xf0, 0x30,
	0x1d, 0xa7, 0x93, 0x13, 0x79, 0x30, 0xc3, 0x21, 0x1c, 0x87, 0xfe, 0x69, 0xd8, 0x19, 0xa7, 0x93,
	0x5c, 0xc6, 0x56, 0x5c, 0xc3, 0xc0, 0x2b, 0x49, 0xe2, 0x46, 0x2b, 0x26, 0x44, 0xe8, 0x1a, 0xe2,
	0xc6, 0xcb, 0xe4, 0xd2, 0xd7, 0xe2, 0x0a, 0xb2, 0x17, 0x5d, 0x92, 0xa4, 0xcf, 0x2d, 0xb1, 0x75,
	0x90, 0xb2, 0xb0, 0x85, 0x87, 0xf4, 0xa4, 0xaf, 0xc5, 0x04, 0xf2, 0x00, 0x69, 0x65, 0x9c, 0xe3,
	0x76, 0xbd, 0x26, 0x0e, 0x81, 0xfa, 0x32, 0xb6, 0xe2, 0x12, 0x7a, 0x0e, 0xc9, 0x4e, 0x46, 0xe9,
	0x92, 0xa2, 0x8c, 0xab, 0xc5, 0x00, 0xb2, 0x65, 0xa5, 0xde, 0x5b, 0x27, 0x71, 0x03, 0x83, 0x39,
	0xd5, 0xb5, 0xfe, 0x91, 0xbd, 0x80, 0x9e, 0xa1, 0xa6, 0xde, 0xb5, 0xaf, 0x0c, 0xcd, 0xdd, 0x57,
	0x07, 0xba, 0xcb, 0x8a, 0x2d, 0xce, 0x00, 0x16, 0x8a, 0xc9, 0x58, 0xe7, 0x80, 0x67, 0x53, 0xbf,
	0xb8, 0xbd, 0xe8, 0x23, 0xdc, 0x1f, 0x05, 0x4d, 0x91, 0xe0, 0x14, 0xfa, 0x2b, 0x53, 0x29, 0x5b,
	0xa9, 0x4d, 0x24, 0xed, 0xa5, 0x18, 0x65, 0xbf, 0x24, 0x16, 0xc9, 0x6d, 0x8a, 0x8f, 0x00, 0x6d,
	0xac, 0xba, 0xd8, 0xfd, 0x65, 0x73, 0x1e, 0x46, 0x07, 0xd9, 0x45, 0x82, 0x33, 0xc8, 0x57, 0x46,
	0xbb, 0x2d, 0xf8, 0x9d, 0xe3, 0x69, 0x80, 0xc5, 0x53, 0x46, 0xda, 0xc1, 0x41, 0x44, 0x82, 0x0f,
	0x90, 0x85, 0x57, 0xfd, 0x87, 0xf5, 0x7a, 0xe4, 0x3f, 0xcc, 0xfd, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x47, 0x51, 0x40, 0x37, 0x3e, 0x02, 0x00, 0x00,
}
